import { MethodCategory, Difficulty, MoneyMethod } from './types';

export const SERVER_IP = 'donutsmp.net';
export const STORE_URL = 'https://store.donutsmp.net';
export const DISCORD_URL = 'https://discord.gg/donutsmp';

export const MONEY_METHODS: MoneyMethod[] = [
  {
    id: '1',
    title: 'Iron Golem Spawners',
    description: 'The gold standard for consistent income. Iron ingots sell for a high price to the shop. Requires a large initial investment for spawners.',
    category: MethodCategory.GRINDING,
    difficulty: Difficulty.MEDIUM,
    investment: 'High ($ millions)',
    estimatedReturn: '$500k - $5M / hr',
    pros: ['Passive income', 'Scalable', 'Reliable sell prices'],
    cons: ['Expensive setup', 'Requires AFK'],
    icon: 'Anvil',
  },
  {
    id: '2',
    title: 'Cactus Farming',
    description: 'A classic massive-scale farm. Build chunks worth of cactus farms. Zero spawner cost, just building materials and time.',
    category: MethodCategory.FARMING,
    difficulty: Difficulty.EASY,
    investment: 'Low (Time intensive)',
    estimatedReturn: '$200k - $1M / hr',
    pros: ['Cheap to start', 'Fully automatic', 'Server staples'],
    cons: ['Massive build size', 'Laggy if too big', 'Lower per-item value'],
    icon: 'Sprout',
  },
  {
    id: '3',
    title: 'Auction House Flipping',
    description: 'Buy low, sell high. Look for underpriced items, god sets, or spawners listed by new players and resell them for profit.',
    category: MethodCategory.ECONOMY,
    difficulty: Difficulty.HARD,
    investment: 'Medium (Cash flow)',
    estimatedReturn: 'Variable ($0 - $10M+)',
    pros: ['Instant profit', 'No building required', 'Exciting'],
    cons: ['High risk', 'Requires market knowledge', 'Inconsistent'],
    icon: 'Gavel',
  },
  {
    id: '4',
    title: 'Blaze Grinders',
    description: 'Excellent mid-tier money making. Blaze rods sell well and provide XP. Good for players transitioning to late game.',
    category: MethodCategory.GRINDING,
    difficulty: Difficulty.MEDIUM,
    investment: 'Medium',
    estimatedReturn: '$300k - $800k / hr',
    pros: ['Good XP source', 'Smaller footprint than IG', 'Active or Passive'],
    cons: ['Requires fuel/setup', 'Less profit than IG'],
    icon: 'Flame',
  },
  {
    id: '5',
    title: 'Voting & Crates',
    description: 'Vote on all links daily. Sell the keys or open them for a chance at spawners and money pouches.',
    category: MethodCategory.OTHER,
    difficulty: Difficulty.EASY,
    investment: 'None',
    estimatedReturn: '$50k - $500k / day',
    pros: ['Free', 'Chance for huge rewards', 'Takes 2 minutes'],
    cons: ['Daily cap', 'RNG dependent'],
    icon: 'Gift',
  },
  {
    id: '6',
    title: 'Sugar Cane / Pumpkin',
    description: 'Manual harvesting or observer-based auto farms. Good for early game capital.',
    category: MethodCategory.FARMING,
    difficulty: Difficulty.EASY,
    investment: 'Very Low',
    estimatedReturn: '$50k - $200k / hr',
    pros: ['Easy to build', 'Good starting money'],
    cons: ['Low ceiling', 'Boring if manual'],
    icon: 'Wheat',
  }
];